language: node_js

node_js:
  - '10'

env:
  - NODE_ENV=test

addons:
  apt:
    packages:
      - xvfb
      - libgconf-2-4

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - rm -rf node_modules npm install

script:
  - npm run ci && cat ./coverage/lcov.info | rm -rf ./coverage
