name: Issue Welcome

on:
  issues:
    types: [opened]

jobs:
  issue-welcome:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'welcome'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: hi @${{ github.event.issue.user.login }}, welcome!
          labels: 'good first issue'
          issue-emoji: '+1, eyes'
  comment:
    runs-on: ubuntu-latest
    steps:
        - name: check-star
          uses: gacts/is-stargazer@v1
          id: check-star
        - name: Create comment
          if: steps.check-star.outputs.is-stargazer != 'true'
          uses: actions-cool/issues-helper@v3
          with:
            actions: 'create-comment'
            token: ${{ secrets.GITHUB_TOKEN }}
            issue-number: ${{ github.event.issue.number }}
            body: |
                Hi @${{ github.event.issue.user.login }}, Please star this repo if you find it useful! Thanks :star:!
                你好 @${{ github.event.issue.user.login }}。如果该仓库对你有用，可以 star 一下，感谢你的 :star:!
            
